wicket_create_account_settings.settings:
  type: config_object
  label: 'Wicket configuration'
  translatable: true
  mapping:
    wicket_create_account_settings_form_browser_title:
      type: label
      label: 'Browser Title'
    wicket_create_account_settings_form_page_title:
      type: label
      label: 'Page Title'
    wicket_create_account_settings_form_page_description:
      type: text
      label: 'Page Description'
